name: Trigger Repository Dispatch

on:
  push:
    branches:
      - main

jobs:
  dispatch:
    strategy:
      matrix:
        repo: ['gtk-rs/gtk4-rs', 'gtk-rs/gtk-rs-core']
    runs-on: ubuntu-latest
    steps:
      - name: Send Repository Dispatch Event
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.TOKEN_PAT }}
          repository: ${{ matrix.repo }}
          event-type: internal-merge-event
